/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.cts.fmsevent.api;

import java.util.List;
import java.util.Optional;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.cts.fmsevent.model.FeedbackAnswer;
import com.fasterxml.jackson.databind.ObjectMapper;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import reactor.core.publisher.Mono;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-03-18T16:20:05.203+05:30")

@Api(value = "feedbackAns", description = "the feedbackAns API")
public interface FeedbackAnsApi {

    Logger log = LoggerFactory.getLogger(FeedbackAnsApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "", nickname = "feedbackAnsPost", notes = "answer feedback", tags={ "participant", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successfully updated answers"),
        @ApiResponse(code = 404, message = "unsuccessful") })
    @RequestMapping(value = "/feedbackAns",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    default Mono<ResponseEntity<Void>> feedbackAnsPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody List<FeedbackAnswer> feedbackAnswer) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default FeedbackAnsApi interface so no example is generated");
        }
        return Mono.just(new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED));
    }

}
